### ISSUE TITLE
Ideas & Discussion

### ISSUE THREAD

**Issue by mhdhejazi** [mhdhejazi/CoronaTracker#15]
Any suggestions or ideas? Feel free to share them here!

**Comment by FluffyDev2019** [comment]
A suggestion or more a request is ability to manually update/refresh data.
As it close to never uptodate.
Not even if I compare Corona Tracker with ex COVID-19Tracker.
Corona Tracker is Always behind in showing numbers/data.

**Comment by Wozinono** [comment]
I love the app! I guess a suggestion would be to add a per capita option for the "Most affected countries" to be able to see what proportion of the population is infected.

**Comment by lor1x** [comment]
The app is never up to date, the website you use to get the data from clearly is not up to par. Maybe get the data from [Bing](https://bing.com/covid) or [Worldometer](https://www.worldometers.info/coronavirus/).
Besides that having an auto refresh and a toggle for Dark Mode would be nice :)

**Comment by anatoly-kor** [comment]
I thought, will be cool to add some widget to Notification Center. With functional get notification when a chosen country or world data updates.

**Comment by Ale111** [comment]
Hi Mohammad and all,
a couple of days ago I found your app (great job congrats!), and I have start to wrote an extension in order to manage the COVID19 data from the DPC (Dipartimento Protezione Civile), the Italian Government Department for People Protection that are published here https://github.com/pcm-dpc/COVID-19. Dataset from DCP are very different from the app data structure and I have done adapters to mantain the data with the original app data struct. I have stopped to dev because in the meantime the app has changed a lots and become to be difficult to be up to date with the changes. 
Anyway if you believe this can be an improvement for the app I can share the code.  
Ale

**Comment by MhdHejazi** [comment]
> A suggestion or more a request is ability to manually update/refresh data.
> As it close to never uptodate.

The app automatically updates every 5 minutes, and when it becomes active. If you suspect it's not updating, try to check [the original source](https://gisanddata.maps.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6) and compare the numbers.

The data source I'm using is very good but not very up to date sometimes. It can be replaced with a different one, but I didn't find a good replacement that has both daily reports and time series.

**Comment by MhdHejazi** [comment]
> I love the app! I guess a suggestion would be to add a per capita option for the "Most affected countries" to be able to see what proportion of the population is infected.

Do you know any data source or a website that shows this number (besides [worldometers](https://www.worldometers.info/coronavirus/#countries))?

**Comment by MhdHejazi** [comment]
> The app is never up to date, the website you use to get the data from clearly is not up to par. Maybe get the data from [Bing](https://bing.com/covid) or [Worldometer](https://www.worldometers.info/coronavirus/).
> Besides that having an auto refresh and a toggle for Dark Mode would be nice :)

The app auto-updates every 5 mins as I said. If you think the data is still old then I guess the data source is the problem. I opened an issue (#18) for using worldometers.info instead of JHU CSSE.

**Comment by MhdHejazi** [comment]
> I thought, will be cool to add some widget to Notification Center. With functional get notification when a chosen country or world data updates.

There is already a widget. Check it out.

![image](https://user-images.githubusercontent.com/121827/76907062-5d7c8680-68b6-11ea-9eca-4922bb9d9ef6.png)

For the notification, I think it's hard to implement without having the app on the app store.

**Comment by MhdHejazi** [comment]
> a couple of days ago I found your app (great job congrats!), and I have start to wrote an extension in order to manage the COVID19 data from the DPC (Dipartimento Protezione Civile), the Italian Government Department for People Protection that are published here https://github.com/pcm-dpc/COVID-19. Dataset from DCP are very different from the app data structure and I have done adapters to mantain the data with the original app data struct. I have stopped to dev because in the meantime the app has changed a lots and become to be difficult to be up to date with the changes.

Sorry about that. The app was changing so fast because it was very new. After the latest changes, I think it's less likely that the app will change in a big way.

Using data from multiple sources is very tricky. You have to be careful or end up with duplicate or conflicting data. If you would like to give it another shot this is a good time, but it would be better if you open an issue to let everybody know that you're working on it.

**Comment by pbeo** [comment]
> > I thought, will be cool to add some widget to Notification Center. With functional get notification when a chosen country or world data updates.
> 
> We already have a widget (Contributed by Piotr Ożóg). Check it out.
> 
> ![image](https://user-images.githubusercontent.com/121827/76907062-5d7c8680-68b6-11ea-9eca-4922bb9d9ef6.png)
> 
> For the notification, I think it's hard to implement without having the app on the app store.

We can implement background fetch and local notification

**Comment by insightmind** [comment]
Suggestion: Instead of just showing the cumulative confirmed cases, maybe also allow to show amount of currently infected cases.

Suggestion: Add possibility to change which statistics are shown on the map. Currently only the cumulative confirmed cases are shown. It may be nice if there was a toggle where you could change it to showing recovered cases, deaths on the map.

**Comment by MhdHejazi** [comment]
@FluffyDev2019 
> A suggestion or more a request is ability to manually update/refresh data.

Added this menu item:

![image](https://user-images.githubusercontent.com/121827/77237978-a9446e00-6bdd-11ea-9cea-40141d37b975.png)

@insightmind The first chart already shows the active cases:

![image](https://user-images.githubusercontent.com/121827/77238064-7484e680-6bde-11ea-8f36-0ab9d2219fa2.png)

But I also added the active cases to the annotation:

![image](https://user-images.githubusercontent.com/121827/77238099-a1d19480-6bde-11ea-973d-fd22c48c9906.png)

And added an option for changing the annotation type:

![image](https://user-images.githubusercontent.com/121827/77238193-35a36080-6bdf-11ea-9161-5f2c99d9d5c2.png)

**Comment by Perezari** [comment]
Version for windows will be great!

**Comment by ppamorim** [comment]
@MhdHejazi Please review my Swiftlint PR again.

**Comment by hardkrash** [comment]
Could you add the trend line with x axis as days since 100 cases.

**Comment by dmyers** [comment]
Is it possible to support MacOS 10.14? It isn't that old and my Mac isn't able to upgrade to 10.15 (2012 Mac Pro).

**Comment by mhdhejazi** [comment]
@hardkrash Added to my list
@dmyers To support 10.14 I'll have to re-write (parts of) the app to use macOS frameworks and stop depending on Catalyst. Not sure I'll be able to do that with the time and resources I have right now, but any contribution is welcome.

**Comment by stevenvar** [comment]
Hi, great job

is there a way to plot the daily new deaths rather than the daily new cases, as we all know new cases are heavily dependent on the number of tests?

Sidetrack remark but it's interesting to see what can be done using catalyst. There is still a lot of slowdowns in some parts of the app though (the map mainly) which I guess is the "fault" of Apple and its integration of iOS APIs.

**Comment by mhdhejazi** [comment]
> is there a way to plot the daily new deaths rather than the daily new cases, as we all know new cases are heavily dependent on the number of tests?

I agree. Added to the list.

For the map, I think the problem is with macOS (see #22). Try to use Maps.app and let me know if it looks any faster.

**Comment by mhdhejazi** [comment]
> Could you add the trend line with x axis as days since 100 cases.

@hardkrash Here you go:

![image](https://user-images.githubusercontent.com/121827/77949969-877b7300-72d0-11ea-949e-9d5a2543fc59.png)


> is there a way to plot the daily new deaths rather than the daily new cases, as we all know new cases are heavily dependent on the number of tests?

@stevenvar I added that too:

![image](https://user-images.githubusercontent.com/121827/77950758-a9292a00-72d1-11ea-912b-60c2ecb473b8.png)

![image](https://user-images.githubusercontent.com/121827/77950766-adedde00-72d1-11ea-9359-58c9b1cf8844.png)

**Comment by jsf030** [comment]
How about another helpful KPI?
 "How long did it take for the number of total confirmed cases to double?" as shown in https://ourworldindata.org/coronavirus#growth-of-cases-how-long-did-it-take-for-the-number-of-confirmed-cases-to-double

**Comment by jsf030** [comment]
The app is really by far the most beautiful on iOS, you should look again if you can publish it on the App Store (#23 ), meanwhile some others have appeared there that don't look like they were developed by authorities.

Nevertheless I still have some suggestions after two days of use, because currently I still have to use several sources.

### Bugs(?):

- It would be great if the countries in the lower two diagrams kept the same colors. It would be confusing if, for example, France is blue on top and green on the bottom.

- In the translation files I read something about the logarithmic representation, but I just can't find it in the app. Am I too stupid or is it not (yet) integrated?

### Features:

- Is it technically possible to color the countries in the map instead of overlaying them with circles? Personally, I would find this much clearer, especially since the colour already reflects the intensity and you don't need the circle size anymore.

- Is there any way to configure the widget to show one country instead of the worldwide development? This is probably more relevant for everyday life outside the app for most people, also because lockdowns are country-specific, political in nature.

**The whole pandemic affects countries with very different conditions, so I find anything that leads to more comparability totally helpful:**

- Yesterday I already suggested integrating the KPI with the number of days until the numbers double. 

- It would be incredibly helpful to also include the KPI "infections per 100,000 inhabitants", this puts the infections in relation to the size of the country and shows the penetration in a meaningful way. For this you need the population figures, which you can find here: https://en.wikipedia.org/wiki/List_of_countries_and_dependencies_by_population 
This would also allow you to express the left yellow number at the top (active infections) as a percentage (percentage of infections in the country population). 

- Both of these KPIs could also be suitable for map display.

**Comment by Di6gEymn** [comment]
Cases per million would be really great. Very few sites have this

Plus, the ability to pick countries to chart and compare with the several charting options already existing would be really cool too!

**Comment by Jerakin** [comment]
Would love a macOS Mojave build

**Comment by Kharg** [comment]
Hello,
how about providing an unsigned IPA at every release so users without a mac can self sign it to use it on iPhone?
I would appreciate it.

**Comment by mhdhejazi** [comment]
Thank you @jsf030 for the great and detailed review!

>you should look again if you can publish it on the App Store (#23 ), meanwhile some others have appeared there that don't look like they were developed by authorities.

When I read this, I checked the App Store to see who was able to publish a similar app. And that's how I knew about this rip-off (#72). So, thank you!

>It would be great if the countries in the lower two diagrams kept the same colors. It would be confusing if, for example, France is blue on top and green on the bottom.

You're totally right. It's embarrassing honestly. Anyway, it's fixed now.

>In the translation files I read something about the logarithmic representation, but I just can't find it in the app. Am I too stupid or is it not (yet) integrated?

You're right. There was an option for using the logarithmic scale in the top affected chart because China was the first with a huge difference to the second. After some time, the option became useless as cases increased in all other countries too. But it looks like we'll need it again now.

>Is it technically possible to color the countries in the map instead of overlaying them with circles? Personally, I would find this much clearer, especially since the colour already reflects the intensity and you don't need the circle size anymore.

This was one of the first things I tried to do when I started the project, but I didn't find a good and easy solution for that, unfortunately. There are no predefined boundaries for the countries in the MapKit. So, one needs to import the boundaries from other sources and create overlays for them in iOS. But then you'll have to deal with many edge cases and different zoom levels, and handle the big memory footprint, ..etc.

> Is there any way to configure the widget to show one country instead of the worldwide development? This is probably more relevant for everyday life outside the app for most people, also because lockdowns are country-specific, political in nature.

@pbeo started working on something similar in a [separate branch](https://github.com/mhdhejazi/CoronaTracker/tree/feature/widget-favorites), but I found out it'll make things more complicated for users as they may need to manually configure a shared group between the app and the widget extension which isn't intuitive for regular users.

>How about another helpful KPI?
"How long did it take for the number of total confirmed cases to double?"

I agree. This is a helpful KPI, and shouldn't be hard to implement if somebody wants to help (anyone?). I added it to my list anyway.

>It would be incredibly helpful to also include the KPI "infections per 100,000 inhabitants"

This is already on my list. I just didn't get time to work on it.

>Both of these KPIs could also be suitable for map display

You mean the overlays?

Thank you again for the great feedback.

**Comment by mhdhejazi** [comment]
@Di6gEymn 
> Plus, the ability to pick countries to chart and compare with the several charting options already existing would be really cool too!

I think this can be done now that we have a separate and big view for every chart.

@Jerakin
>Would love a macOS Mojave build

This isn't possible right now as Catalyst isn't available for macOS Mojave, and creating a native macOS app isn't a top priority. But I'm happy to assist if someone wants to give it a try.

@Kharg 
>how about providing an unsigned IPA at every release so users without a mac can self sign it to use it on iPhone?

AFAIK, It's not possible to export an unsigned IPA from Xcode. Any idea how that can be done?

**Comment by jsf030** [comment]
In return, thank you for your detailed answer!

> You're right. There was an option for using the logarithmic scale in the top affected chart because China was the first with a huge difference to the second. After some time, the option became useless as cases increased in all other countries too. But it looks like we'll need it again now.
>
About the logarithmic representation: In fact, this does not only help to be able to display curves that are out of control. In fact, a "perfect" exponential function is also displayed exactly linear on a logarithmic representation. So if people in many countries are now hoping to finally see the trend reversal in the statistics, they will find it there particularly descriptive. 

> This was one of the first things I tried to do when I started the project, but I didn't find a good and easy solution for that, unfortunately. There are no predefined boundaries for the countries in the MapKit. So, one needs to import the boundaries from other sources and create overlays for them in iOS. But then you'll have to deal with many edge cases and different zoom levels, and handle the big memory footprint, ..etc.
> 
Okay, that's too bad. Because that way heat maps etc. could be visualized much better. I could of course suggest APIs like Mapbox, or even OSM. But I also understand your project in a way that you want to create a native experience, a kind of showcase, what is possible with Swift and Catalyst. 

> @pbeo started working on something similar in a [separate branch](https://github.com/mhdhejazi/CoronaTracker/tree/feature/widget-favorites), but I found out it'll make things more complicated for users as they may need to manually configure a shared group between the app and the widget extension which isn't intuitive for regular users.
> 
I don't think it's necessarily too complicated, I think it's in good proportion to the added value. But in the end I only express wishes and suggestions here and I am already very grateful.

> I agree. This is a helpful KPI, and shouldn't be hard to implement if somebody wants to help (anyone?). I added it to my list anyway.
> 
I would if I could. But whoever takes this gets a heart emoticon from me. 

> You mean the overlays?
> 
I meant the colored countries or regions I suggested above, because this way it can also show trends on the map. It is probably more difficult with circles. 

> Thank you again for the great feedback.
>
Not for that! I have to thank you.

**Comment by mhdhejazi** [comment]
>Okay, that's too bad. Because that way heat maps etc. could be visualized much better. I could of course suggest APIs like Mapbox, or even OSM. But I also understand your project in a way that you want to create a native experience, a kind of showcase, what is possible with Swift and Catalyst.

MapBox was one of the options. They have boundaries and custom styles that would allow doing this. But I thought it'd be far harder to implement than using the native MapKit with annotations.

>I don't think it's necessarily too complicated, I think it's in good proportion to the added value. But in the end I only express wishes and suggestions here and I am already very grateful.

You can try the feature in the mentioned branch. It's out of date now but should work.

**Comment by mhdhejazi** [comment]
I added a logarithmic scale option to 3 charts.

![image](https://user-images.githubusercontent.com/121827/78726110-d2813000-7939-11ea-8da8-581d9516bc87.png)

**Comment by srt10coupe** [comment]
Do you want to build an Android version?

**Comment by mhdhejazi** [comment]
> Do you want to build an Android version?

Not in the plan. This project is only focused on iOS and macOS.

**Comment by srt10coupe** [comment]
> > Do you want to build an Android version?
> 
> Not in the plan. This project is only focused on iOS and macOS.

thx
---
what do you think of a possibility to save the selection of a country or region and not to reset after every update to World?

**Comment by mhdhejazi** [comment]
Yeah, it makes sense. It's on my list.

**Comment by FluffyDev2019** [comment]
Hi again @mhdhejazi 
Is it possible to be able to add/country to get access within app data simular to this?
(Sorry for the Swedish language in ex)
![66F2EACD-59EF-435A-8D45-0D436AE9BF98](https://user-images.githubusercontent.com/49336613/80528928-fcf16680-8996-11ea-8f8f-71f5169d12a1.jpeg)
![A6FAC430-F519-4D3F-92FD-CC3BE872FD2D](https://user-images.githubusercontent.com/49336613/80528965-08449200-8997-11ea-8955-3a65c7444c64.png)

Taken from here:
https://experience.arcgis.com/experience/09f821667ce64bf7be6f9f87457ed9aa?utm_source=ios-app.expressen.se

Those statistics would be a great contribution to apps information flow and benefit alot of users in there strive for information.

**Comment by FluffyDev2019** [comment]
Other ex of local information 
![6A606B6A-A073-4D35-87DF-72552E299DBA](https://user-images.githubusercontent.com/49336613/80529430-bea87700-8997-11ea-8836-731369dfc078.jpeg)
![292A16ED-175B-4C19-8C2F-0CBB2ED77DBA](https://user-images.githubusercontent.com/49336613/80529488-d2ec7400-8997-11ea-911b-2dcf5fceb908.jpeg)

**Comment by lor1x** [comment]
@mhdhejazi I would like to contribute in translation, how could I help?

**Comment by mhdhejazi** [comment]
> Other ex of local information
> <img src="https://user-images.githubusercontent.com/49336613/80529430-bea87700-8997-11ea-8836-731369dfc078.jpeg" width="200" />

We already have province-level data for Sweden. This is basically the same chart:
![image](https://user-images.githubusercontent.com/121827/80689792-822f6500-8ad6-11ea-8eda-17c60be5a01a.png)

And when you zoom in you can see all the provinces:
![image](https://user-images.githubusercontent.com/121827/80690658-cc651600-8ad7-11ea-874e-88c259372c98.png)

As for the statistics in the first image, we need a source that has similar data for other countries before adding a section for this in the app.

**Comment by mhdhejazi** [comment]
@lor1x 
> I would like to contribute in translation, how could I help?

There is a project on poeditor.com for translations. You can easily add/update the translations from the website. 

The project link: https://poeditor.com/join/project/UTZyE0GKiT

Also, you may want to check #26.

**Comment by FluffyDev2019** [comment]
> > Other ex of local information
> > <img alt="" width="200" src="https://user-images.githubusercontent.com/49336613/80529430-bea87700-8997-11ea-8836-731369dfc078.jpeg">
> 
> We already have province-level data for Sweden. This is basically the same chart:
> ![image](https://user-images.githubusercontent.com/121827/80689792-822f6500-8ad6-11ea-8eda-17c60be5a01a.png)
> 
> And when you zoom in you can see all the provinces:
> ![image](https://user-images.githubusercontent.com/121827/80690658-cc651600-8ad7-11ea-874e-88c259372c98.png)
> 
> As for the statistics in the first image, we need a source that has similar data for other countries before adding a section for this in the app.

I can't see any of that regional information in my installed 1.7 version.
It looks like this -> 
![F649287D-FE1C-4167-A1DB-6C51DC5D6BBC](https://user-images.githubusercontent.com/49336613/80699458-45666c80-8adc-11ea-85cb-4386cd6c756d.png)

And no charts for regional data showing up either in app.
+ it would be nice to be able to see somewhere in CT, a version nr. (Version 1.7).

**Comment by FluffyDev2019** [comment]
@mhdhejazi The apperence of regions does Only appear IF I change my system language to English, if I have Swedish chosen (as is Default to most Swedes), no Regional "Dots" and no information to it is shown.

Shouldn't Regional dots/data be available even if other languages then English as system language is chosen?

**Comment by FluffyDev2019** [comment]
With English set as system language:

![5ED8F99A-EB3E-4AA7-A404-C0D072DE9212](https://user-images.githubusercontent.com/49336613/80809395-e67b2300-8bc1-11ea-9b65-3bdf71619ffa.png)

With Swedish set as system language:

![2B80E78C-AF2E-4965-AA81-6DCE90790942](https://user-images.githubusercontent.com/49336613/80809442-f8f55c80-8bc1-11ea-96a0-10c31fea14e2.png)

**Comment by mhdhejazi** [comment]
@FluffyDev2019
>The apperence of regions does Only appear IF I change my system language to English, if I have Swedish chosen (as is Default to most Swedes), no Regional "Dots" and no information to it is shown.

Nice catch. This looks like a bug. I created a separate issue for it. Thank you for reporting the problem.

**Comment by mhdhejazi** [comment]
I think this thread has gotten too big now. I'm going to close it, but please feel free to open a new issue for any idea you want to discuss or issue you face.

Thank you to all who shared their feedback here 👍 Stay safe and healthy!
