### ISSUE TITLE
Adding unit tests?

### ISSUE THREAD

**Issue by ejewik** [mhdhejazi/CoronaTracker#24]
Hi, I really like your project and appreciate that you're doing this! Would adding some tests to the app be beneficial? I want to help but this is my first time trying to contribute, and was wondering if this would be something I could help with. Thank you!

**Comment by MhdHejazi** [comment]
I admire your willingness to contribute. Unit tests are always useful, although not really necessary for this app. But you can absolutely work on them if you wish.

**Comment by ejewik** [comment]
Okay! I may be a little slow because I'm new to this but I'll try my best.

**Comment by MhdHejazi** [comment]
No worries. Please take your time.

**Comment by ejewik** [comment]
Hi again, I'm trying to write a test for the center method of the coordinate class but am having trouble understanding exactly what's going on. I had thought that if I instantiated two Coordinates like so: Coordinate(latitude: 10, longitude: 0) and Coordinate(latitude: -10, longitude: 0), that the center Coordinate returned would have a latitude of 0 and longitude of 0 but the method returned a latitude of 10. What is this method returning exactly?

**Comment by mhdhejazi** [comment]
Let's say we have 4 locations (A, B, C, D):
```
A     
         

                      B

        C

D
```
We calculate the center location. Let it be X :
```
A     
         

           X           B

        C

D
```
The problem with X is that it doesn't represent a real/existing location, and therefore we can't use it. We need to find the closest exiting location to it. That's why we calculate the distances between each location and X and choose the one with the shortest distance.
```swift
public static func center(of coordinates: [Coordinate]) -> Coordinate {
    /// 1. Calculate X
    let totals = coordinates.reduce((latitude: 0.0, longitude: 0.0)) {
        ($0.latitude + $1.latitude, $0.longitude + $1.longitude)
    }

    let center = Coordinate(latitude: totals.latitude / Double(coordinates.count),
                            longitude: totals.longitude / Double(coordinates.count))
    /// 2. Choose the closest location to X
    return coordinates.min {
        center.distance(from: $0) < center.distance(from: $1)
    }!
}
```

For the unit tests, maybe it's not a good idea to work on them now. You will have to spend a lot of time trying to understand the code before being able to write the tests. Especially when most of the code isn't documented (Sorry for that). So, if you ask me, I'd suggest delaying the work on unit tests until the code base is ready for that. Maybe working on smaller features and improvements in the app would be easier and help you understand the code better.

**Comment by ejewik** [comment]
Thank you for the detailed answer! And it's completely alright that it's not documented yet. I'll see what other parts of the app I can contribute to though my skillset is rather limited.
